version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    tty: true
    volumes:
      - ./node:/app
    networks:
      - node_net
    ports:
      - "3000:3000"
    command: "node index.js"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
    - node_net
networks:
  node_net:
    driver: bridge