version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: nkziz/laravel:prod
    container_name: laravel
    networks:
      - laranet
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: nkziz/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8000:80

networks:
  laranet:
    driver: bridge