FROM nginx:1.15.0-alpine

WORKDIR /app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY html /usr/share/nginx/html/

RUN mkdir /var/www/html -p && touch /var/www/html/index.php && echo "<?php phpinfo();" > /var/www/html/index.php
